import Collection from './Collection';
import FeaturedImage from './FeaturedImage';
import FeaturedMedia from './FeaturedMedia';
import ProductOption from './ProductOption';
import SellingPlan from './SellingPlan';
import SellingPlanAllocation from './SellingPlanAllocation';
import SellingPlanGroup from './SellingPlanGroup';
import Variant from './Variant';

export default interface Product {
  available: boolean;
  collections: Collection[];
  compare_at_price: number;
  compare_at_price_max: number;
  compare_at_price_min: number;
  compare_at_price_varies: boolean;
  content: string;
  created_at: string;
  description: string;
  featured_image: string;
  featured_media: FeaturedMedia;
  first_available_variant: Variant;
  gift_card?: boolean;
  handle: string;
  has_only_default_variant: boolean;
  id: number;
  images: FeaturedImage[];
  media: FeaturedMedia[];
  metafields: any[];
  options: string[];
  options_with_values: ProductOption[];
  price: number;
  price_max: number;
  price_min: number;
  price_varies: boolean;
  published_at: string;
  quantity_price_breaks_configured?: boolean;
  requires_selling_plan: boolean;
  selected_or_first_available_variant: Variant;
  selected_selling_plan: SellingPlan;
  selected_selling_plan_allocation: SellingPlanAllocation;
  selected_variant: Variant;
  selling_plan_groups: SellingPlanGroup[];
  tags: string[];
  template_suffix: string;
  title: string;
  type: string;
  url: string;
  variants: Variant[];
  vendor: string;
}
